name: CI

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:  
    - master
    - develop 

jobs:
  CI:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Installing Cocoapods
      run: |
       pod install
       pod update

    - name: Installing and Updating FastLane
      run: gem install fastlane
 
    - name: Running Tests
      run: fastlane tests
  CD:
    needs: [CI]
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master

    - name: Installing Cocoapods
      run: |
       pod install
       pod update

    - name: Installing and Updating FastLane
      run: gem install fastlane
    - name: Fastlane Build and Deploy
      run: 
       fastlane beta     
