name: Deploy_to_App_Store

on:
  push:
    -master 

jobs:
  CI:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Installing Cocoapods
      run: |
       pod install
       pod update

    - name: Installing FastLane
      run: | 
       bundle install
       bundle update fastlane
         
 
    - name: Running Tests
      run: bundle exec fastlane release    
