name: Deploy_to_App_Store

on:
  push:
    branches:
    - master 

jobs:
  Deploy_to_App_Store:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    
    - name: Installing Cocoapods
      run: |
       pod install
       pod update  
 
    - name: Releasing my little app to the world
      run: fastlane release
